### ISSUE TITLE
Container command arguments incorrect for tyk-pump

### ISSUE THREAD

**Issue by dijitali** [TykTechnologies/tyk-kubernetes#17]
The current [`tyk-pump.yaml`](https://github.com/TykTechnologies/tyk-kubernetes/blob/ba3458383c7c88b2f219c5b4b8919c9ab896837c/tyk/deployments/tyk-pump.yaml#L21) causes the pump to crash and the following error is logged:
```
➜  tyk-kubernetes git:(master) ✗ kubectl logs deployment/tyk-pump --namespace tyk
tyk-pump: error: unknown long flag '--c', try --help
```

Changing the `tyk-pump.yaml` to a single dash:
```
command: ["/opt/tyk-pump/tyk-pump", "-c=/etc/tyk-pump/pump.conf"]
```
causes another error:
```
➜  tyk-kubernetes git:(master) ✗ kubectl logs deployment/tyk-pump --namespace tyk
time="Oct 23 13:31:43" level=info msg="## Tyk Analytics Pump, v0.5.4 ##"
time="Oct 23 13:31:43" level=fatal msg="Couldn't load configuration file: open =/etc/tyk-pump/pump.conf: no such file or directory"
```

The correct syntax is to specify the config location via an argument:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tyk-pump
  namespace: tyk
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tyk-pump
    spec:
      containers:
      - image: tykio/tyk-pump-docker-pub:latest
        imagePullPolicy: Always
        name: tyk-pump
        workingDir: "/opt/tyk-pump"
        env:
          - name: REDIGOCLUSTER_SHARDCOUNT
            value: "128"
        command: ["/opt/tyk-pump/tyk-pump"]
        args: ["-c", "/etc/tyk-pump/pump.conf"]
        volumeMounts:
          - name: tyk-pump-conf
            mountPath: /etc/tyk-pump
      volumes:
        - name: tyk-pump-conf
          configMap:
            name: tyk-pump-conf
            items:
              - key: pump.conf
                path: pump.conf
```

**Comment by mischcon** [comment]
Changing the `command` to `["/opt/tyk-pump/tyk-pump", "-c", "/etc/tyk-pump/pump.conf"]` resolved the issue for me.

Full config:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tyk-pump
  namespace: tyk
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tyk-pump
    spec:
      containers:
      - image: tykio/tyk-pump-docker-pub:latest
        imagePullPolicy: Always
        name: tyk-pump
        workingDir: "/opt/tyk-pump"
        env:
          - name: REDIGOCLUSTER_SHARDCOUNT
            value: "128"
        command: ["/opt/tyk-pump/tyk-pump", "-c", "/etc/tyk-pump/pump.conf"]
        volumeMounts:
          - name: tyk-pump-conf
            mountPath: /etc/tyk-pump
      volumes:
        - name: tyk-pump-conf
          configMap:
            name: tyk-pump-conf
            items:
              - key: pump.conf
                path: pump.conf
```
